### Week 8 Activities


- Build logistic regression model (**without using scikit-learn**) to predict the rightmost column/feature of `dataset/ionosphere.data.csv` based on remaining features. 
- Please note: it's a binary classification task. 
- Try: 
    - i) batch gradient descent, 
    - ii) stochastic gradient descent, and 
    - iii) mini-batch gradient descent algorithms. 
- Comment on the performances based on learning rate, batch size, etc. 
- Show binary classification model performance in terms of Accuracy, Precision, Recall, F1-score, ROC (with AUC).

In [80]:
import pandas as pd

In [81]:
df = pd.read_csv('datasets/ionosphere.data.csv')

In [82]:
df.head()

1  0  0.99539  -0.05889  0.85243  0.02306  0.83398  -0.37708      1.1  \
0  1  0  1.00000  -0.18829  0.93035 -0.36156 -0.10868  -0.93597  1.00000   
1  1  0  1.00000  -0.03365  1.00000  0.00485  1.00000  -0.12062  0.88965   
2  1  0  1.00000  -0.45161  1.00000  1.00000  0.71216  -1.00000  0.00000   
3  1  0  1.00000  -0.02401  0.94140  0.06531  0.92106  -0.23255  0.77152   
4  1  0  0.02337  -0.00592 -0.09924 -0.11949 -0.00763  -0.11824  0.14706   

   0.03760  ...  -0.51171  0.41078  -0.46168  0.21266  -0.34090  0.42267  \
0 -0.04549  ...  -0.26569 -0.20468  -0.18401 -0.19040  -0.11593 -0.16626   
1  0.01198  ...  -0.40220  0.58984  -0.22145  0.43100  -0.17365  0.60436   
2  0.00000  ...   0.90695  0.51613   1.00000  1.00000  -0.20099  0.25682   
3 -0.16399  ...  -0.65158  0.13290  -0.53206  0.02431  -0.62197 -0.05707   
4  0.06637  ...  -0.01535 -0.03240   0.09223 -0.07859   0.00732  0.00000   

   -0.54487  0.18641  -0.45300  g  
0  -0.06288 -0.13738  -0.02447  b  
1  -0.24180  0.56045  -0.38238  g  
2   1.00000 -0.32382   1.00000  b  
3  -0.59573 -0.04608  -0.65697  g  
4   0.00000 -0.00039   0.12011  b  

[5 rows x 35 columns]

In [83]:
df.shape

(350, 35)

In [84]:
# encode the last column 
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(handle_unknown='ignore',drop='first', sparse_output=False)
encoded_col = encoder.fit_transform(df[['g']])
encoded_col


array([[0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],

In [85]:
encoder.categories_

[array(['b', 'g'], dtype=object)]

In [86]:
encoder_list = []
ohe_df_features = []
ohe_df_feature = pd.DataFrame(encoded_col, columns=list(encoder.categories_[0][1:]))
ohe_df_features.append(ohe_df_feature)
ohe_dataset = pd.concat(ohe_df_features,axis=1)
ohe_dataset.index = df.index
#drop the categorical feature columns
df = df.drop(columns=['g'] )

#merge rest of the dataset with these new onehot features
df = df.join(ohe_dataset)
df.head()

1  0  0.99539  -0.05889  0.85243  0.02306  0.83398  -0.37708      1.1  \
0  1  0  1.00000  -0.18829  0.93035 -0.36156 -0.10868  -0.93597  1.00000   
1  1  0  1.00000  -0.03365  1.00000  0.00485  1.00000  -0.12062  0.88965   
2  1  0  1.00000  -0.45161  1.00000  1.00000  0.71216  -1.00000  0.00000   
3  1  0  1.00000  -0.02401  0.94140  0.06531  0.92106  -0.23255  0.77152   
4  1  0  0.02337  -0.00592 -0.09924 -0.11949 -0.00763  -0.11824  0.14706   

   0.03760  ...  -0.51171  0.41078  -0.46168  0.21266  -0.34090  0.42267  \
0 -0.04549  ...  -0.26569 -0.20468  -0.18401 -0.19040  -0.11593 -0.16626   
1  0.01198  ...  -0.40220  0.58984  -0.22145  0.43100  -0.17365  0.60436   
2  0.00000  ...   0.90695  0.51613   1.00000  1.00000  -0.20099  0.25682   
3 -0.16399  ...  -0.65158  0.13290  -0.53206  0.02431  -0.62197 -0.05707   
4  0.06637  ...  -0.01535 -0.03240   0.09223 -0.07859   0.00732  0.00000   

   -0.54487  0.18641  -0.45300    g  
0  -0.06288 -0.13738  -0.02447  0.0  
1  -0.24180  0.56045  -0.38238  1.0  
2   1.00000 -0.32382   1.00000  0.0  
3  -0.59573 -0.04608  -0.65697  1.0  
4   0.00000 -0.00039   0.12011  0.0  

[5 rows x 35 columns]

In [87]:
X = df.drop(columns=['g'])
X.head()

1  0  0.99539  -0.05889  0.85243  0.02306  0.83398  -0.37708      1.1  \
0  1  0  1.00000  -0.18829  0.93035 -0.36156 -0.10868  -0.93597  1.00000   
1  1  0  1.00000  -0.03365  1.00000  0.00485  1.00000  -0.12062  0.88965   
2  1  0  1.00000  -0.45161  1.00000  1.00000  0.71216  -1.00000  0.00000   
3  1  0  1.00000  -0.02401  0.94140  0.06531  0.92106  -0.23255  0.77152   
4  1  0  0.02337  -0.00592 -0.09924 -0.11949 -0.00763  -0.11824  0.14706   

   0.03760  ...  0.56811  -0.51171  0.41078  -0.46168  0.21266  -0.34090  \
0 -0.04549  ... -0.20332  -0.26569 -0.20468  -0.18401 -0.19040  -0.11593   
1  0.01198  ...  0.57528  -0.40220  0.58984  -0.22145  0.43100  -0.17365   
2  0.00000  ...  1.00000   0.90695  0.51613   1.00000  1.00000  -0.20099   
3 -0.16399  ...  0.03286  -0.65158  0.13290  -0.53206  0.02431  -0.62197   
4  0.06637  ...  0.03513  -0.01535 -0.03240   0.09223 -0.07859   0.00732   

   0.42267  -0.54487  0.18641  -0.45300  
0 -0.16626  -0.06288 -0.13738  -0.02447  
1  0.60436  -0.24180  0.56045  -0.38238  
2  0.25682   1.00000 -0.32382   1.00000  
3 -0.05707  -0.59573 -0.04608  -0.65697  
4  0.00000   0.00000 -0.00039   0.12011  

[5 rows x 34 columns]

In [88]:
y = df[['g']]
y.head()

g
0  0.0
1  1.0
2  0.0
3  1.0
4  0.0

In [89]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(280, 34) (280, 1)
(70, 34) (70, 1)


- use skylearn to compare against the model used without

In [90]:
from sklearn import linear_model
model = linear_model.LinearRegression()
model.fit(X=X_train,y=y_train)

LinearRegression()

In [91]:
beta_1 = model.coef_
beta_0 = model.intercept_
print(f'The regression model is y = {beta_1}x + {beta_0}')

The regression model is y = [[ 3.08731615e-01  7.71241643e+11  1.65064579e-01  1.77575488e-01
   1.31330042e-01  1.59442213e-01  1.26636822e-01  1.56553759e-01
   1.53509217e-01  4.23596554e-02 -4.84563487e-02 -3.86131388e-02
  -8.43475085e-02  6.45132107e-02  9.16369692e-02 -5.43534780e-03
   3.75822429e-02  3.79191739e-02 -1.53774952e-01  1.19093976e-01
  -1.73201534e-03 -2.54230608e-01  1.78765825e-01  9.84608274e-02
   8.81995005e-02  7.95574225e-02 -1.42120782e-01  2.39590476e-02
   6.23552302e-02  5.04655136e-02  1.70459166e-01 -1.42775533e-02
  -1.28427422e-01 -2.30102539e-01]]x + [0.01331987]


In [92]:
import numpy as np
X_train_np = X_train.to_numpy(dtype=X_train.dtypes[0])
X0 = np.hstack((np.ones([X_train.shape[0],1]), X_train_np))

print(X0)
print(X0.shape)

[[ 1.  1.  0. ...  0.  0.  0.]
 [ 1.  1.  0. ... -1.  0.  0.]
 [ 1.  1.  0. ...  0.  0.  0.]
 ...
 [ 1.  1.  0. ...  0.  0.  0.]
 [ 1.  1.  0. ...  0.  0.  0.]
 [ 1.  1.  0. ...  0.  1.  0.]]
(280, 35)


/var/folders/_2/0wh94zd11cj6smgr_57jgfyc0000gn/T/ipykernel_2793/176166140.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  X_train_np = X_train.to_numpy(dtype=X_train.dtypes[0])


In [93]:
beta = np.random.random_sample(size = (35,1)) 
print(beta)
beta = np.dot(np.dot(np.linalg.pinv(np.dot(X0.T,X0)), X0.T), y_train)
print(beta)

[[0.21732012]
 [0.86825002]
 [0.4128621 ]
 [0.80669583]
 [0.73808495]
 [0.32573283]
 [0.79612223]
 [0.10726732]
 [0.18812253]
 [0.11117208]
 [0.22972158]
 [0.72943545]
 [0.59788122]
 [0.9842176 ]
 [0.78108856]
 [0.36236819]
 [0.26445619]
 [0.13966692]
 [0.01235151]
 [0.09442128]
 [0.8824138 ]
 [0.50081053]
 [0.62937997]
 [0.57378295]
 [0.76315027]
 [0.56657658]
 [0.61147632]
 [0.64114991]
 [0.03148526]
 [0.14410244]
 [0.34658765]
 [0.63615258]
 [0.55602782]
 [0.76295981]
 [0.81476887]]
[[ 2.91651366e-01]
 [ 4.57140889e-01]
 [ 3.77517664e-17]
 [ 7.73937599e-02]
 [ 9.70954920e-02]
 [ 3.47133014e-02]
 [ 1.49072380e-01]
 [ 2.68792192e-02]
 [ 1.06544189e-01]
 [ 6.52755509e-02]
 [-7.21939313e-02]
 [-4.34209474e-02]
 [-1.44195002e-01]
 [-7.75424577e-02]
 [ 8.57608580e-02]
 [ 1.16664198e-01]
 [ 8.20737979e-02]
 [ 1.16713348e-01]
 [ 8.90243465e-02]
 [-2.22795239e-01]
 [ 1.44427386e-01]
 [-9.39072070e-02]
 [-1.21491995e-01]
 [ 1.16081459e-01]
 [ 2.48679798e-01]
 [-1.27468116e-02]
 [-2.10173139e-

In [94]:
beta.shape

(35, 1)

In [95]:
print(f"Our regression model is: y_hat = {beta[1]}x + {beta[0]}")

Our regression model is: y_hat = [0.45714089]x + [0.29165137]


In [96]:


X_test_np = X_test.to_numpy(dtype=X_test.dtypes[0])
x_test_with_bias = np.hstack((np.ones([X_test.shape[0],1]), X_test_np))
print(x_test_with_bias)

[[ 1.  0.  0. ...  1.  0.  0.]
 [ 1.  1.  0. ...  1.  1.  0.]
 [ 1.  1.  0. ...  0.  0.  0.]
 ...
 [ 1.  1.  0. ...  0.  0.  0.]
 [ 1.  0.  0. ...  1. -1.  1.]
 [ 1.  1.  0. ...  0.  0.  0.]]


/var/folders/_2/0wh94zd11cj6smgr_57jgfyc0000gn/T/ipykernel_2793/423094190.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  X_test_np = X_test.to_numpy(dtype=X_test.dtypes[0])


In [97]:
x_test_with_bias.shape

(70, 35)

### using batch gradient descent

In [98]:
# initialize beta 
# [beta_0, beta_1]^T
beta = np.random.random_sample(size = (X0.shape[1],1))
# beta_old will store beta scores from previous iterations
beta_old = beta.copy()

# num of sample
n = X.shape[0]
# learning rate 
alpha = 0.1
reach_convergence = False
delta = 0
eps = 1e-4

# other gradient update loop
i = 0
while reach_convergence == False:
    gradient = (1/n)* np.dot(X0.T , (np.dot(X0,beta) - y_train))
    beta = beta - alpha * gradient

    #convergence test
    delta = np.sqrt(np.sum( (beta_old - beta)**2 ) )
    if delta < eps:
        reach_convergence = True
    if i % 1000 == 0:
        print(f'Epoch {i+1}: beta = [{beta[0]}, {beta[1]}, delta = {delta}')
    beta_old = beta
    i = i + 1
print(f'Epoch {i+1}: Batch Gradient Descent Algo Converged')
print(f'Solution: beta = [{beta[0]}, {beta[1]}, delta = {delta}')

Epoch 1: beta = [[0.08733205], [0.69611997], delta = 0.3058095888910299


Epoch 1001: beta = [[0.23849678], [0.50800454], delta = 0.0002547002544158071
Epoch 1659: Batch Gradient Descent Algo Converged
Solution: beta = [[0.27009425], [0.47805036], delta = 9.990056854599345e-05


In [99]:
# now predict with it
y_pred_batch = np.dot(x_test_with_bias,beta)
y_pred_batch.shape

(70, 1)

In [100]:
rmse = np.sqrt(np.sum((y_test-y_pred_batch)**2)/len(y_test))
print(f'RMSE = {rmse}')

RMSE = g    0.387351
dtype: float64


/Users/natalienguyen/Developer/Machine Learning/venv-machine-learning/lib/python3.9/site-packages/numpy/_core/fromnumeric.py:84: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)


In [101]:
r2score = 1 - (np.sum((y_test-y_pred_batch)**2)/ np.sum((y_test-np.mean(y_test))**2))
print(f'R2-score = {r2score}')

R2-score = g    0.357343
dtype: float64
