### Week 8 Activities


- Build logistic regression model (**without using scikit-learn**) to predict the rightmost column/feature of `dataset/ionosphere.data.csv` based on remaining features. 
- Please note: it's a binary classification task. 
- Try: 
    - i) batch gradient descent, 
    - ii) stochastic gradient descent, and 
    - iii) mini-batch gradient descent algorithms. 
- Comment on the performances based on learning rate, batch size, etc. 
- Show binary classification model performance in terms of Accuracy, Precision, Recall, F1-score, ROC (with AUC).

In [187]:
import pandas as pd

In [188]:
df = pd.read_csv('datasets/ionosphere.data.csv')

In [189]:
df.head()

1  0  0.99539  -0.05889  0.85243  0.02306  0.83398  -0.37708      1.1  \
0  1  0  1.00000  -0.18829  0.93035 -0.36156 -0.10868  -0.93597  1.00000   
1  1  0  1.00000  -0.03365  1.00000  0.00485  1.00000  -0.12062  0.88965   
2  1  0  1.00000  -0.45161  1.00000  1.00000  0.71216  -1.00000  0.00000   
3  1  0  1.00000  -0.02401  0.94140  0.06531  0.92106  -0.23255  0.77152   
4  1  0  0.02337  -0.00592 -0.09924 -0.11949 -0.00763  -0.11824  0.14706   

   0.03760  ...  -0.51171  0.41078  -0.46168  0.21266  -0.34090  0.42267  \
0 -0.04549  ...  -0.26569 -0.20468  -0.18401 -0.19040  -0.11593 -0.16626   
1  0.01198  ...  -0.40220  0.58984  -0.22145  0.43100  -0.17365  0.60436   
2  0.00000  ...   0.90695  0.51613   1.00000  1.00000  -0.20099  0.25682   
3 -0.16399  ...  -0.65158  0.13290  -0.53206  0.02431  -0.62197 -0.05707   
4  0.06637  ...  -0.01535 -0.03240   0.09223 -0.07859   0.00732  0.00000   

   -0.54487  0.18641  -0.45300  g  
0  -0.06288 -0.13738  -0.02447  b  
1  -0.24180  0.56045  -0.38238  g  
2   1.00000 -0.32382   1.00000  b  
3  -0.59573 -0.04608  -0.65697  g  
4   0.00000 -0.00039   0.12011  b  

[5 rows x 35 columns]

In [190]:
df.shape

(350, 35)

In [191]:
# encode the last column 
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(handle_unknown='ignore',drop='first', sparse_output=False)
encoded_col = encoder.fit_transform(df[['g']])
encoded_col


array([[0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],

In [192]:
encoder.categories_

[array(['b', 'g'], dtype=object)]

In [193]:
encoder_list = []
ohe_df_features = []
ohe_df_feature = pd.DataFrame(encoded_col, columns=list(encoder.categories_[0][1:]))
ohe_df_features.append(ohe_df_feature)
ohe_dataset = pd.concat(ohe_df_features,axis=1)
ohe_dataset.index = df.index
#drop the categorical feature columns
df = df.drop(columns=['g'] )

#merge rest of the dataset with these new onehot features
df = df.join(ohe_dataset)
df.head()

1  0  0.99539  -0.05889  0.85243  0.02306  0.83398  -0.37708      1.1  \
0  1  0  1.00000  -0.18829  0.93035 -0.36156 -0.10868  -0.93597  1.00000   
1  1  0  1.00000  -0.03365  1.00000  0.00485  1.00000  -0.12062  0.88965   
2  1  0  1.00000  -0.45161  1.00000  1.00000  0.71216  -1.00000  0.00000   
3  1  0  1.00000  -0.02401  0.94140  0.06531  0.92106  -0.23255  0.77152   
4  1  0  0.02337  -0.00592 -0.09924 -0.11949 -0.00763  -0.11824  0.14706   

   0.03760  ...  -0.51171  0.41078  -0.46168  0.21266  -0.34090  0.42267  \
0 -0.04549  ...  -0.26569 -0.20468  -0.18401 -0.19040  -0.11593 -0.16626   
1  0.01198  ...  -0.40220  0.58984  -0.22145  0.43100  -0.17365  0.60436   
2  0.00000  ...   0.90695  0.51613   1.00000  1.00000  -0.20099  0.25682   
3 -0.16399  ...  -0.65158  0.13290  -0.53206  0.02431  -0.62197 -0.05707   
4  0.06637  ...  -0.01535 -0.03240   0.09223 -0.07859   0.00732  0.00000   

   -0.54487  0.18641  -0.45300    g  
0  -0.06288 -0.13738  -0.02447  0.0  
1  -0.24180  0.56045  -0.38238  1.0  
2   1.00000 -0.32382   1.00000  0.0  
3  -0.59573 -0.04608  -0.65697  1.0  
4   0.00000 -0.00039   0.12011  0.0  

[5 rows x 35 columns]

In [194]:
X = df.drop(columns=['g'])
X.head()

1  0  0.99539  -0.05889  0.85243  0.02306  0.83398  -0.37708      1.1  \
0  1  0  1.00000  -0.18829  0.93035 -0.36156 -0.10868  -0.93597  1.00000   
1  1  0  1.00000  -0.03365  1.00000  0.00485  1.00000  -0.12062  0.88965   
2  1  0  1.00000  -0.45161  1.00000  1.00000  0.71216  -1.00000  0.00000   
3  1  0  1.00000  -0.02401  0.94140  0.06531  0.92106  -0.23255  0.77152   
4  1  0  0.02337  -0.00592 -0.09924 -0.11949 -0.00763  -0.11824  0.14706   

   0.03760  ...  0.56811  -0.51171  0.41078  -0.46168  0.21266  -0.34090  \
0 -0.04549  ... -0.20332  -0.26569 -0.20468  -0.18401 -0.19040  -0.11593   
1  0.01198  ...  0.57528  -0.40220  0.58984  -0.22145  0.43100  -0.17365   
2  0.00000  ...  1.00000   0.90695  0.51613   1.00000  1.00000  -0.20099   
3 -0.16399  ...  0.03286  -0.65158  0.13290  -0.53206  0.02431  -0.62197   
4  0.06637  ...  0.03513  -0.01535 -0.03240   0.09223 -0.07859   0.00732   

   0.42267  -0.54487  0.18641  -0.45300  
0 -0.16626  -0.06288 -0.13738  -0.02447  
1  0.60436  -0.24180  0.56045  -0.38238  
2  0.25682   1.00000 -0.32382   1.00000  
3 -0.05707  -0.59573 -0.04608  -0.65697  
4  0.00000   0.00000 -0.00039   0.12011  

[5 rows x 34 columns]

In [195]:
y = df[['g']]
y.head()

g
0  0.0
1  1.0
2  0.0
3  1.0
4  0.0

In [196]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(280, 34) (280, 1)
(70, 34) (70, 1)


In [197]:
import numpy as np
X_train_np = X_train.to_numpy(dtype=X_train.dtypes[0])
X0 = np.hstack((np.ones([X_train.shape[0],1]), X_train_np))

print(X0)
print(X0.shape)

[[ 1.  1.  0. ...  0.  0.  0.]
 [ 1.  1.  0. ... -1.  0.  0.]
 [ 1.  1.  0. ...  0.  0.  0.]
 ...
 [ 1.  1.  0. ...  0.  0.  0.]
 [ 1.  1.  0. ...  0.  0.  0.]
 [ 1.  1.  0. ...  0.  1.  0.]]
(280, 35)


/var/folders/_2/0wh94zd11cj6smgr_57jgfyc0000gn/T/ipykernel_2793/176166140.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  X_train_np = X_train.to_numpy(dtype=X_train.dtypes[0])


In [198]:
beta = np.random.random_sample(size = (35,1)) 
print(beta)
beta = np.dot(np.dot(np.linalg.pinv(np.dot(X0.T,X0)), X0.T), y_train)
print(beta)

[[0.30858257]
 [0.71460228]
 [0.25957391]
 [0.36399766]
 [0.97028822]
 [0.62521903]
 [0.71381   ]
 [0.16927362]
 [0.74902261]
 [0.50635205]
 [0.34168416]
 [0.90253079]
 [0.5561381 ]
 [0.37327663]
 [0.97095971]
 [0.24894874]
 [0.2968762 ]
 [0.52295047]
 [0.45256836]
 [0.75916921]
 [0.18140959]
 [0.82214448]
 [0.2206545 ]
 [0.18255589]
 [0.10075291]
 [0.58122317]
 [0.02557707]
 [0.93917759]
 [0.60667319]
 [0.55862429]
 [0.41061684]
 [0.72252992]
 [0.29045801]
 [0.98013227]
 [0.51778838]]
[[ 2.91651366e-01]
 [ 4.57140889e-01]
 [ 3.77517664e-17]
 [ 7.73937599e-02]
 [ 9.70954920e-02]
 [ 3.47133014e-02]
 [ 1.49072380e-01]
 [ 2.68792192e-02]
 [ 1.06544189e-01]
 [ 6.52755509e-02]
 [-7.21939313e-02]
 [-4.34209474e-02]
 [-1.44195002e-01]
 [-7.75424577e-02]
 [ 8.57608580e-02]
 [ 1.16664198e-01]
 [ 8.20737979e-02]
 [ 1.16713348e-01]
 [ 8.90243465e-02]
 [-2.22795239e-01]
 [ 1.44427386e-01]
 [-9.39072070e-02]
 [-1.21491995e-01]
 [ 1.16081459e-01]
 [ 2.48679798e-01]
 [-1.27468116e-02]
 [-2.10173139e-

In [199]:
beta.shape

(35, 1)

In [200]:
print(f"Our regression model is: y_hat = {beta[1]}x + {beta[0]}")

Our regression model is: y_hat = [0.45714089]x + [0.29165137]


In [201]:


X_test_np = X_test.to_numpy(dtype=X_test.dtypes[0])
x_test_with_bias = np.hstack((np.ones([X_test.shape[0],1]), X_test_np))
print(x_test_with_bias)

[[ 1.  0.  0. ...  1.  0.  0.]
 [ 1.  1.  0. ...  1.  1.  0.]
 [ 1.  1.  0. ...  0.  0.  0.]
 ...
 [ 1.  1.  0. ...  0.  0.  0.]
 [ 1.  0.  0. ...  1. -1.  1.]
 [ 1.  1.  0. ...  0.  0.  0.]]


/var/folders/_2/0wh94zd11cj6smgr_57jgfyc0000gn/T/ipykernel_2793/423094190.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  X_test_np = X_test.to_numpy(dtype=X_test.dtypes[0])


In [202]:
x_test_with_bias.shape

(70, 35)

### Using batch gradient descent

In [203]:
# initialize beta 
# [beta_0, beta_1]^T
beta = np.random.random_sample(size = (X0.shape[1],1))
# beta_old will store beta scores from previous iterations
beta_old = beta.copy()

# num of sample
n = X.shape[0]
# learning rate 
alpha = 0.1
reach_convergence = False
delta = 0
eps = 1e-4

# other gradient update loop
i = 0
while reach_convergence == False:
    gradient = (1/n)* np.dot(X0.T , (np.dot(X0,beta) - y_train))
    beta = beta - alpha * gradient

    #convergence test
    delta = np.sqrt(np.sum( (beta_old - beta)**2 ) )
    if delta < eps:
        reach_convergence = True
    if i % 1000 == 0:
        print(f'Epoch {i+1}: beta = [{beta[0]}, {beta[1]}, delta = {delta}')
    beta_old = beta
    i = i + 1
print(f'Epoch {i+1}: Batch Gradient Descent Algo Converged')
print(f'Solution: beta = [{beta[0]}, {beta[1]}, delta = {delta}')

Epoch 1: beta = [[0.42091641], [0.23060253], delta = 0.3204462259179937


Epoch 1001: beta = [[0.33026668], [0.41759689], delta = 0.00017547767172438488
Epoch 1307: Batch Gradient Descent Algo Converged
Solution: beta = [[0.31531843], [0.4329268], delta = 9.988556654301604e-05


In [204]:
# now predict with it
y_pred_batch = np.dot(x_test_with_bias,beta)
y_pred_batch.shape

(70, 1)

In [205]:
rmse = np.sqrt(np.sum((y_test-y_pred_batch)**2)/len(y_test))
print(f'RMSE = {rmse}')

RMSE = g    0.391413
dtype: float64


/Users/natalienguyen/Developer/Machine Learning/venv-machine-learning/lib/python3.9/site-packages/numpy/_core/fromnumeric.py:84: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)


In [206]:
r2score = 1 - (np.sum((y_test-y_pred_batch)**2)/ np.sum((y_test-np.mean(y_test))**2))
print(f'R2-score = {r2score}')

R2-score = g    0.343793
dtype: float64


### Stochastic gradient descent

In [207]:
# initialize beta
# [beta_0, beta_1]^T
beta = np.random.random_sample(size = (X0.shape[1],1)) 
print(beta.shape)
# this will store beta scores from previous iteration
beta_old = beta.copy() 

(35, 1)


In [208]:
#num of sample
n = X0.shape[0]
#learning rate
alpha = 0.01
reach_convergence = False
delta = 0 #distance between two betas
eps = 1e-6

In [209]:
#shuffle training set, or keep a record of shuffled indices
indices = np.arange(n)
np.random.shuffle(indices)

In [210]:
#The gradient update loop
i = 0
iter = 0
num_epochs = 0
while reach_convergence == False:
    #grab a sample
    x_sample = X0[indices[i],:].reshape(1,-1) #a row vector, not a column vector
    #compute gradient
    gradient = np.dot(x_sample.T, (np.dot(x_sample, beta) - y_train.iloc[int(indices[i])].values[0]))
    beta = beta - alpha * gradient

    #convergence test
    delta = np.sqrt(np.sum( (beta_old - beta)**2 ) )
    if delta < eps:
        reach_convergence = True
    if iter % 1000 == 0:
        print(f'Step {iter+1}: beta = [{beta[0]}, {beta[1]}, delta = {delta}')
    beta_old = beta
    i = i + 1
    iter = iter + 1
    if i >= n: # next epoch begins
        np.random.shuffle(indices)
        num_epochs = num_epochs + 1
        i = 0 #reset
print(f'Step {iter+1}, Epoch {num_epochs}: Stochastic Gradient Descent Algo Converged')
print(f'Solution: beta = [{beta[0]}, {beta[1]}, delta = {delta}')

Step 1: beta = [[0.52264863], [0.13729973], delta = 0.004907200382411154
Step 1001: beta = [[0.43559637], [0.27382971], delta = 0.00901542619688162
Step 2001: beta = [[0.43218927], [0.32549141], delta = 0.004528899262246173
Step 3001: beta = [[0.39223896], [0.33405633], delta = 0.04553446274335373
Step 4001: beta = [[0.37458887], [0.35861576], delta = 0.0038500573585545476
Step 5001: beta = [[0.34719028], [0.36767716], delta = 0.022451031323217956
Step 6001: beta = [[0.3426929], [0.3869185], delta = 0.0039019104435788258
Step 7001: beta = [[0.34826336], [0.41408427], delta = 0.0034295021027179635
Step 8001: beta = [[0.30900374], [0.38241811], delta = 0.004453014206616602
Step 9001: beta = [[0.32346345], [0.42489175], delta = 0.0038047757213068517
Step 10001: beta = [[0.31557556], [0.43295613], delta = 0.009503600501771826
Step 11001: beta = [[0.30890829], [0.43832717], delta = 0.003647582158228438
Step 12001: beta = [[0.32791558], [0.45616063], delta = 0.0077597709003181786
Step 13001:

In [211]:
y_pred_stochastic = np.dot(x_test_with_bias,beta)
y_pred_stochastic.shape

(70, 1)

In [212]:
rmse = np.sqrt(np.sum((y_test-y_pred_stochastic)**2)/len(y_test))
print(f'RMSE = {rmse}')

RMSE = g    0.400306
dtype: float64


In [213]:
r2score = 1 - (np.sum((y_test-y_pred_stochastic)**2)/ np.sum((y_test-np.mean(y_test))**2))
print(f'R2-score = {r2score}')

R2-score = g    0.313636
dtype: float64


### Mini Batch Gradient Descent

In [220]:
#initialize beta
beta = np.random.random_sample(size = (X0.shape[1],1)) #[beta_0, beta_1]^T
print(beta.shape)
beta_old = beta.copy() #this will store beta scores from previous iteration

(35, 1)


In [221]:
#num of sample
n = X.shape[0]
#learning rate
alpha = 0.01
reach_convergence = False
delta = 0 #distance between two betas
eps = 1e-3
b = 5 #batch_size

In [222]:
#shuffle training set, or keep a record of shuffled indices
indices = np.arange(n)
np.random.shuffle(indices)

In [227]:
# create the batch of indices
batch_of_indices = []
if n%b == 0:
    num_of_batches = int(n / b)
else:
    num_of_batches = n // b + 1
idx = 0
for _ in range(num_of_batches):
    batch_of_indices.append(indices[idx:idx+b])
    idx = idx + b



In [228]:
i = 0
iter = 0
num_epochs = 0
while reach_convergence == False:
    #grab a batch of samples
    X_sample = X.iloc[batch_of_indices[i], :]

    y_sample = y_train.iloc[batch_of_indices[i]].values.reshape(-1, 1)

    #print(f'X_sample.shape = {X_sample.shape}, y_sample.shape = {y_sample.shape}')
    
    #compute gradient
    gradient = (1/b)* np.dot(X_sample.T , (np.dot(X_sample,beta) - y_sample))
    beta = beta - alpha * gradient

    #convergence test
    delta = np.sqrt(np.sum( (beta_old - beta)**2 ) )
    if delta < eps:
        reach_convergence = True
    if iter % 1000 == 0:
        print(f'Step {iter+1}: beta = [{beta[0]}, {beta[1]}, delta = {delta}')
    beta_old = beta
    i = i + 1
    iter = iter + 1
    if i >= num_of_batches: # next epoch begins
        np.random.shuffle(indices)
        #create the batch of indices (again)
        batch_of_indices = []
        if n%b == 0:
            num_of_batches = int(n / b)
        else:
            num_of_batches = n // b + 1
        idx = 0
        for _ in range(num_of_batches):
            batch_of_indices.append(indices[idx:idx+b])
            idx = idx + b
        #increment epoch counter
        num_epochs = num_epochs + 1
        i = 0 #reset
print(f'Step {iter+1}, Epoch {num_epochs}: Mini-batch Gradient Descent Algo (with batch_size = {b}) Converged')
print(f'Solution: beta = [{beta[0]}, {beta[1]}, delta = {delta}')

IndexError: positional indexers are out-of-bounds